// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pombpsabgvzowgmwruxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvbWJwc2FiZ3Z6b3dnbXdydXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0Njc5MjAsImV4cCI6MjA2MDA0MzkyMH0.6qYOOJqNAzrO8OkkiQu0S2kt5gpQbmgECJVqWR71iJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);